#!/bin/sh
# Temporary review/diagnostic build stamp generator. Regenerated each build.
# Usage:
#   ./tool/sva_build_stamp.sh --mode release --alarmkit-force-off 1 --review 1
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="release"
FORCE_OFF="0"
REVIEW="1"
STAGE="R1"

while [ $# -gt 0 ]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --alarmkit-force-off) FORCE_OFF="$2"; shift 2 ;;
    --review) REVIEW="$2"; shift 2 ;;
    --stage) STAGE="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

SHA="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
BRANCH_SLUG="$(printf '%s' "$BRANCH" | tr '/ ' '--')"
STAMP="${BRANCH_SLUG}-${SHA}"
if ! git -C "$ROOT" diff --quiet 2>/dev/null || ! git -C "$ROOT" diff --cached --quiet 2>/dev/null; then
  STAMP="${STAMP}-dirty"
fi
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
ALARMKIT_STARTUP="disabled"
if [ "$FORCE_OFF" = "0" ]; then
  ALARMKIT_STARTUP="passive"
fi

JSON="$ROOT/tool/sva_build_stamp.json"
XCCONFIG="$ROOT/ios/Flutter/sva_build_stamp.xcconfig"

cat >"$JSON" <<EOF
{
  "SVA_GIT_SHA": "$SHA",
  "SVA_GIT_BRANCH": "$BRANCH",
  "SVA_BUILD_STAMP": "$STAMP",
  "SVA_BUILD_MODE": "$MODE",
  "SVA_BUILD_TIME": "$BUILD_TIME",
  "SVA_ALARMKIT_FORCE_OFF": "$FORCE_OFF",
  "SVA_ALARMKIT_STARTUP": "$ALARMKIT_STARTUP",
  "SVA_REVIEW_BUILD": "$( [ "$REVIEW" = "1" ] && echo true || echo false )",
  "SVA_DIAG_STAGE": "$STAGE"
}
EOF

cat >"$XCCONFIG" <<EOF
// Generated by tool/sva_build_stamp.sh — do not commit.
SVA_BUILD_STAMP=$STAMP
SVA_BUILD_MODE=$MODE
SVA_BUILD_TIME=$BUILD_TIME
SVA_ALARMKIT_FORCE_OFF=$FORCE_OFF
SVA_ALARMKIT_STARTUP=$ALARMKIT_STARTUP
SVA_DIAG_STAGE=$STAGE
INFOPLIST_KEY_SVABuildStamp=$(printf '%s' "$STAMP")
INFOPLIST_KEY_SVABuildMode=$(printf '%s' "$MODE")
INFOPLIST_KEY_SVABuildTime=$(printf '%s' "$BUILD_TIME")
INFOPLIST_KEY_SVAAlarmKitForceOff=$(printf '%s' "$FORCE_OFF")
INFOPLIST_KEY_SVAAlarmKitStartup=$(printf '%s' "$ALARMKIT_STARTUP")
INFOPLIST_KEY_SVADiagStage=$(printf '%s' "$STAGE")
EOF

SWIFT_GEN="$ROOT/ios/Runner/SvaBuildStamp.generated.swift"
cat >"$SWIFT_GEN" <<EOF
// Generated by tool/sva_build_stamp.sh — do not commit.
import Foundation

enum SvaBuildStampGenerated {
  static let stamp = "$STAMP"
  static let mode = "$MODE"
  static let buildTime = "$BUILD_TIME"
  static let alarmKitStartup = "$ALARMKIT_STARTUP"
  static let alarmKitForceOff = "$FORCE_OFF"
  static let diagStage = "$STAGE"
  static let gitSha = "$SHA"
  static let gitBranch = "$BRANCH"
  static let binaryUuid = "pending"
}
EOF

echo "Wrote $SWIFT_GEN"
echo "SVA_BUILD=$STAMP"
echo "SVA_MODE=$MODE"
echo "SVA_ALARMKIT_STARTUP=$ALARMKIT_STARTUP"
echo "SVA_DIAG_STAGE=$STAGE"
echo "SVA_BUILD_TIME=$BUILD_TIME"
echo "Wrote $JSON"
echo "Wrote $XCCONFIG"
